spring.application.name=demo

# SQL DB settings
spring.datasource.url=jdbc:mysql://mysql_container:3306/classicmodels?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=springboot
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Swagger settings
springdoc.swagger-ui.oauth.client-id=springboot_client
springdoc.swagger-ui.oauth.realm=backend
springdoc.swagger-ui.oauth.app-name=SpringBootApp
springdoc.swagger-ui.oauth.scope-separator=,
springdoc.swagger-ui.oauth.scopes=openid,profile,email

# Logging settings
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

# Keycloak settings
keycloak.issuer=http://keycloak_container:4000/realms/martin-realm
keycloak.authorization_endpoint=${keycloak.issuer}/protocol/openid-connect/auth
keycloak.serverUrl=http://keycloak_container:4000
keycloak.realm=martin-realm
keycloak.resource=martin-root
keycloak.credentials.secret=martin-secret

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.issuer}/protocol/openid-connect/certs

keycloak.protectedUrl=/api/protected
keycloak.publicUrl=/api/public
# RocketMQ settings
rocketmq.name-server=rocketmq_container:9876
