version: '3.8'
services:
  mysql:
    container_name: mysql_container
    build: ./docker_example_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "classicmodels"
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
  springboot:
    container_name: springboot_container
    build: ./docker_example_springboot
    ports:
      - "8000:8080"
    depends_on:
      - mysql
      - keycloak
    networks:
       - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/classicmodels?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springboot
      SPRING_DATASOURCE_PASSWORD: admin
      
  keycloak:
    container_name: keycloak_container
    build: ./docker_example_keycloak
    ports:
      - "4000:4000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - my-network
    depends_on:
      - mysql
volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge