spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak
            client-secret: your_client_secret
            client-name: frontend
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            authorization-uri: http://keycloak_container:4000/auth/realms/backend
            user-name-attribute: keycloak